#!/bin/sh
export GOROOT=/usr/local/go
export GOPATH=`pwd`/../

printf "\033[1;33m"

echo "Begin to build......"
$GOROOT/bin/go build --ldflags '-linkmode external -extldflags "-static"' -o mainapi mainapi.go
echo "build finished"

printf "\033[m"
